import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, CalendarDays, Car, Plus, TrendingUp, Users } from "lucide-react";
import PageShell from "../components/Layout";
import { PortalLayout } from "../components/Portal";
import { currency } from "../data/cars";
import { dashboardApi } from "../services/api";

export function Dashboard() {
  const [stats, setStats] = useState({ totalCars: 0, totalBookings: 0, totalUsers: 0, totalRevenue: 0, recentBookings: [] });
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    dashboardApi.stats().then(data => setStats(data)).catch(() => {}).finally(() => setLoading(false));
  }, []);
  const fmtRev = (n) => { if (n >= 100000) return `\u20b9${(n / 100000).toFixed(2)}L`; return `\u20b9${currency(n)}`; };
  return <PageShell footer={false}><PortalLayout title="Overview" eyebrow="ADMIN SPACE" type="admin" action={<Link className="button button-dark" to="/add-car?new=true"><Plus size={17} /> Add a car</Link>}><div className="admin-stats"><div><span>Total revenue</span><strong>{loading ? "..." : fmtRev(stats.totalRevenue)}</strong><small><TrendingUp size={14} /> All time</small></div><div><span>Total bookings</span><strong>{loading ? "..." : stats.totalBookings}</strong><small>Across all users</small></div><div><span>Cars listed</span><strong>{loading ? "..." : stats.totalCars}</strong><small>On the platform</small></div><div><span>Total users</span><strong>{loading ? "..." : stats.totalUsers}</strong><small>Registered members</small></div></div><div className="admin-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">PERFORMANCE</p><h3>Revenue overview</h3></div><select><option>Last 6 months</option></select></div><div className="bar-chart">{[48, 58, 46, 78, 63, 91].map((height, i) => <div key={i}><i style={{height: `${height}%`}} /><span>{["Mar", "Apr", "May", "Jun", "Jul", "Aug"][i]}</span></div>)}</div></section><section className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">PLATFORM</p><h3>Quick stats</h3></div></div><div className="activity-item"><span className="avatar orange"><Users size={16} /></span><p><strong>{stats.totalUsers} registered users</strong><br /><small>Platform members</small></p></div><div className="activity-item"><span className="avatar green"><Car size={16} /></span><p><strong>{stats.totalCars} cars listed</strong><br /><small>Available on DriveOn</small></p></div><div className="activity-item"><span className="avatar blue"><CalendarDays size={16} /></span><p><strong>{stats.totalBookings} total bookings</strong><br /><small>All time bookings</small></p></div></section></div><section id="bookings" className="panel booking-table-panel"><div className="panel-heading"><div><p className="eyebrow">AT A GLANCE</p><h3>Recent bookings</h3></div><Link className="text-button" to="/my-bookings">All bookings <ArrowRight size={16} /></Link></div><table><thead><tr><th>Guest</th><th>Car</th><th>Total</th><th>Status</th></tr></thead><tbody>{stats.recentBookings.length === 0 ? <tr><td colSpan="4" style={{ textAlign: "center", padding: "30px", color: "#999" }}>{loading ? "Loading..." : "No bookings yet"}</td></tr> : stats.recentBookings.map((b, i) => <tr key={i}><td>{b.user?.name || "Guest"}</td><td>{b.car?.name || "N/A"}</td><td>\u20b9{currency(b.totalPrice || 0)}</td><td><span className={`status ${b.status === "completed" ? "completed" : "upcoming"}`}>{b.status || "Pending"}</span></td></tr>)}</tbody></table></section></PortalLayout></PageShell>;
}
