import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, Calendar, ChevronDown, Plus, Star, TrendingUp } from "lucide-react";
import PageShell from "../components/Layout";
import { PortalLayout } from "../components/Portal";
import { cars } from "../data/cars";
import { getMember } from "../services/session";

export function HostDashboard() { 
  const member = getMember();
  const firstName = (member && member.name) ? member.name.split(' ')[0] : "there";

  return <PageShell footer={false}><PortalLayout title="Your host space" eyebrow={`GOOD MORNING, ${firstName.toUpperCase()}`} type="host" action={<Link className="button button-dark" to="/add-car?new=true"><Plus size={17} /> Add a car</Link>}><div className="host-dashboard-header"><div><span>August earnings</span><strong>\u20b931,450</strong><small><TrendingUp size={14} /> You're up 18% from July</small></div><div><span>Booked days</span><strong>14 <small>/ 22 available</small></strong><i><b /></i></div><div><span>Guest rating</span><strong><Star size={17} fill="currentColor" /> 4.96</strong><small>From 46 trips</small></div></div><section className="host-booking-alert"><img src={cars[0].image} alt="" /><div><p className="eyebrow">NEXT PICK-UP \u00b7 TOMORROW</p><h3>{firstName} is picking up your Tesla Model 3.</h3><p><Calendar size={15} /> Check your bookings for details</p></div><button className="button button-dark">View booking <ArrowRight size={16} /></button></section><div className="host-dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">YOUR FLEET</p><h3>Cars on DriveOn</h3></div><Link className="text-button" to="/add-car">Manage cars <ArrowRight size={16} /></Link></div><div className="host-car-row"><img src={cars[0].image} alt="" /><div><strong>Tesla Model 3</strong><span><i className="available-dot" /> Available \u00b7 \u20b94,890/day</span></div><span>8 bookings</span><Link to="/edit-car/urban-s"><ArrowUpRight size={17} /></Link></div><div className="host-car-row"><img src={cars[2].image} alt="" /><div><strong>Jeep Compass</strong><span><i className="busy-dot" /> Currently booked</span></div><span>6 bookings</span><Link to="/edit-car/coastline"><ArrowUpRight size={17} /></Link></div></section><section className="panel calendar-panel"><div className="panel-heading"><div><p className="eyebrow">AVAILABILITY</p><h3>{new Date().toLocaleString("default", { month: "long", year: "numeric" })}</h3></div><button><ChevronDown size={17} /></button></div><div className="calendar-days">{Array.from({length: 31}, (_, i) => <span className={[3,4,5,10,11,12,16,17].includes(i) ? "booked" : i === (new Date().getDate() - 1) ? "today" : ""} key={i}>{i+1}</span>)}</div><p><i className="available-dot" /> Available <i className="busy-dot" /> Booked</p></section></div></PortalLayout></PageShell>; 
}
