export { Home } from "./Home";
export { Cars } from "./Cars";
export { CarDetails } from "./CarDetails";
export { RazorpayCheckout } from "./RazorpayCheckout";
export { Booking } from "./Booking";
export { CompareCars } from "./CompareCars";
export { About } from "./About";
export { BecomeHost } from "./BecomeHost";
export { Contact } from "./Contact";
export { HelpCenter } from "./HelpCenter";
export { Login } from "./Login";
export { Register } from "./Register";
export { ForgotPassword, ResetPassword } from "./ForgotPassword";
export { UserDashboard } from "./UserDashboard";
export { Dashboard } from "./Dashboard";
export { MyBookings } from "./MyBookings";
export { Favorites } from "./Favorites";
export { Profile } from "./Profile";
export { PaymentHistory } from "./PaymentHistory";
export { PaymentReceipt } from "./PaymentReceipt";
export { HostDashboard } from "./HostDashboard";
export { AddCar } from "./AddCar";
export { EditCar } from "./EditCar";
export { HostApplications } from "./HostApplications";
export { ManageUsers } from "./ManageUsers";
export { Terms, PrivacyPolicy } from "./Legal";
export { NotFound } from "./NotFound";
